dist: xenial

language: java

jdk:
- openjdk17

env:
  global:
     - NODE_VERSION="14.17.6"
     - PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin/:$PATH
     - APPNAME="fairspace"
     - ORG="fairspace"
     - ARTIFACT_BUILD_FILE=""
     - BUILD_SCRIPTS_REPO="thehyve/fairspace-build-scripts"
     - ACCOUNT_CONFIG_DIR="./.travis"
     - RELEASE_BRANCH="release"
     - SNAPSHOT_BRANCH="dev"
     - DOCKER_USERNAME="fairspace"
     - GITHUB_USERNAME="fairspace-ci"
     - GCP_PROJECT="fairspace-207108"
     - GIT_TAG_FILES_OVERRIDE="charts/fairspace/Chart.yaml charts/fairspace/values.yaml projects/"
     - SHOULD_DEPLOY=false
     # DEPLOYMENT RELATED VARIABLES - REQUIRED IF SHOULD_DEPLOY=true
     # - DEPLOYMENT_CONFIG_REPO="thehyve/fairspace-config-private"
     # - SNAPSHOT_CONTEXT="gke_fairspace-207108_europe-west1-b_fairspacecicluster"
     # - SNAPSHOT_CLUSTER_NAME="fairspacecicluster"
     # - SNAPSHOT_CLUSTER_ZONE="europe-west1-b"
     # - RELEASE_CONTEXT="gke_fairspace-207108_europe-west1-b_fairspacecicluster"
     # - RELEASE_CLUSTER_NAME="fairspacecicluster"
     # - RELEASE_CLUSTER_ZONE="europe-west1-b"

     # DOCKER_PASSWORD=
     - secure: "FJTXKY792rdmQZ6DLU5Dlm1W9ZAmFwBFWEJDO4dLJySBO/clUUV0OfRkNX4OaachKUlRCFGxYbXaXCioYtMTVg54aD1d+hjBO5azPzUiT8V2mz2w3MkvxsvnvivziJtcSfol/PNHQdEK8qZhZ9IwdCnQM9LQ3YVwv9tkNpR//qNmUjA4ZdcbQrBLQ63wm/UX2vCo4D3/J24TfCJrmlu9AyoIAqiFsRczsQGixQLRzeRgwH3yFgACZrMt42ySrx4rL+Yi3Ro/ZftY+YrZPRs+wrObh++OmdzjQWXH4KBg8HTFEIJXYMOVnpG0OSdNO7j7oVS8qVRHJmFAG0VHrmSIMMbjU+3js3SVJxtwXRc3xEPJzKzhtyqGaQa5mr3pI1Q8YingcsEBEpWOh9zXBzJm1uh7JhgTgcEbBwQl12/SctMjejyAFFqVHhlSAEzuDBwTkXLiv6z6sF+SUpww8I6eKmQrJUN1HVPm9+n1nsBy1j3PIM0RmTAf+jZCuAMDg0Dg0dlY/in/Jz1k/QuFDbJ4ura4YBBQ315UDoki5rucDi2poxq9YoAaMpMouso9ilAwOms3guVaU/rgOHZsmIPqv2ccH6FEoOh2UeEq3RCGbprLAj88f2rcGNPaHNWRkeek31c+TI9JZPmeL5eh5tJ64cN+feVVk8lbqNWtR9VHRrI="

    # GITHUB_PASSWORD=....
     - secure: "bTrWqQd94u/MSqFPiKm4xgRNUWnsZi/xRur0T3SFklT5hCfzJC/32etgSPJ/b3k9kNWJrE+Za6bWEpHgDnPEILUVOTylmcIarE4bL902u/5b+BF2d/6YRM5CiXIDohn0XdVs4FneuP3BGFXA49Uqt177oxyhLdpLn65ootTUjAYUVLsgjexv7nyy14u1mP3+64w6QVbIRZNGXVz3PyyY6mTB77Ppbi3bJLcGRblvD/RxXC8BFk6PpXczb/qwrgNh5jWCVdIXCgyJywq/lHEr/DU0A5NIrICnC0CyZEYiOjxmOrfrpA6xOsHhZGz266P9yIEO59NxNPc8leeW2WcwVxopWV5FKpMWkPLFQHHbjvhmoScg1gcHhAGWempOaCFvZrRswA0rvPt/3NkehfBnq7xyF08KZmoQ8Upd1yo3vRPEhevSYSwGgh6fR6oZM9IFBLTpjSGQBYR1FBey2xfA82sjuQrQfj0B9BF2sVdL1dNKHT8X409ftasK/8d0iMVsuKqXTneFs0rakpHypggiYysQBWvJfMO4L6u4sYe2E4xscucV6IxnV4f+wPVKGla4RlRfhbNwwXnZSahtoC5fQ8yK0iG8oDAnbJHK8Et+LXM1X4LYjTAZxzRvaDEDAzOTH2z5XWXvu94mRZtQUerw/W1P5hCIcDk34xsWF/hdHWI="

cache:
  directories:
  - $HOME/downloads
  - $HOME/.cache
  - $HOME/.gradle

before_install:
  - nvm install $NODE_VERSION
  - export KUBE_CONFIG_ENC_KEY=$encrypted_6c9f30024cb1_key
  - export KUBE_CONFIG_ENC_IV=$encrypted_6c9f30024cb1_iv
  - git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
  - export BUILD_SCRIPTS_DIR=$(pwd)/ci
  - 'if [[ "$SHOULD_DEPLOY" = "true" ]]; then git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$DEPLOYMENT_CONFIG_REPO ci-config ; fi'
  - 'if [[ "$SHOULD_DEPLOY" = "true" ]]; then export DEPLOYMENT_CONFIG_DIR="$(pwd)/ci-config/fairspace" ; fi'
  - 'if [[ "$SHOULD_DEPLOY" = "true" ]] && [[ "$TRAVIS_BRANCH" = "$SNAPSHOT_BRANCH" ]]; then export ALLOW_SNAPSHOTS=1 DEPLOY_TARGET=ci DEPLOY_PLATFORM="GCP" KUBERNETES_CONTEXT="$SNAPSHOT_CONTEXT" CLUSTER_NAME="$SNAPSHOT_CLUSTER_NAME" CLUSTER_ZONE="$SNAPSHOT_CLUSTER_ZONE" ; fi'
  - 'if [[ "$SHOULD_DEPLOY" = "true" ]] && [[ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" ]]; then export DEPLOY_TARGET=ci DEPLOY_PLATFORM="GCP" KUBERNETES_CONTEXT="$RELEASE_CONTEXT" CLUSTER_NAME="$RELEASE_CLUSTER_NAME" CLUSTER_ZONE="$RELEASE_CLUSTER_ZONE" ; fi'
  - export INFRASTRUCTURE_PLATFORM="${DEPLOY_PLATFORM:-NONE}"
  - source ./ci/setup_env.sh
  - 'if [[ "$SHOULD_RELEASE" ]]; then export OIDC_AUTH_VERSION=$VERSION; fi'
  - 'if [[ "$SHOULD_RELEASE" ]] ; then export NEED_INTERNAL_HELM=1 ; fi'

jobs:
  include:
    - stage: build
      name: Build projects
      install:
      - ci/gcp/install.sh
      - ci/gcp/login.sh
      script:
      - .travis/build.sh projects/saturn
      - .travis/build.sh projects/pluto [mercury]
      - .travis/build.sh docker/fairspace-ssl-proxy
      - export SANITIZED_BRANCH=$(echo $TRAVIS_BRANCH | sed 's/\//_/g')
    - stage: build
      cache: false
      name: Build helm charts
      install:
      - source charts/.travis/install.sh
      script:
      - charts/.travis/build.sh
    - if: branch = release and type != pull_request
      cache: false
      stage: Versioning
      name: Set tag and update version
      script:
      - "ci/versioning/add_tag_to_git.sh"
      - "ci/versioning/set_next_version.sh"
    - stage: deploy
      cache: false
      if: env(SHOULD_DEPLOY) = true and branch = dev and type != pull_request
      install:
      - source charts/.travis/install.sh
      script:
      - travis_wait ci/helm/deploy.sh $DEPLOY_TARGET -f projects/saturn/views.yaml
    - if: branch = documentation and type != pull_request
      install:
        - docs/.travis/install.sh
      script:
        - docs/.travis/publish.sh

notifications:
  slack:
    rooms:
     - secure: "d7qU4xOhiwy19tI+BrE5PGZLKf8yVlv0QWkBiQ+M4g0UO8Ge4a+ZrYP33ZF0lgsfMM0jRaxnLjT9wge0om3uDTwnGKJejAi+AWCU83c3IwLsaIMFhk22vMFXB46U8tUxt4hKsvQFCURKSMTILPUGBqnn18Nf9Yy+4/o43aSwVbvR4sQ4RSdC/+hn/FSQSqY7RHutyhC7DiVDnwKCNYE1I7YU1vEnLawKKS97qJ6tXgE9GQJuupDUy4RC9U5bPIVK0fBbmWv37qWowZ8sNqY/QvzJ9xwXW6NS9eON91VqalNU+pvV0soExMTAnW5oj302WDlYM5mGKNLd3E/gq0jHxQvI4M/oNMZvqZmPI7pyEEjhazN3RdnUqj1fDpNSED4zsC38h0LDK7CEJcTDk4QEDWthlFxz4CaUsKblr5dZBxX6g2PkOhZk8k/PSLORNtcuDH/2X/IFv2Oegy5tOlcEOH/QY6HYW0ayJMV3WtLUN4MivdT00EQs10Fk1Zc6oSM1jpEcYq7lSj3PiXyXsM9Yong2Y1nORAe81CWosIUXit6SdVcWM0ztNEmGk8ViZZqntEsYg975Fr5XB8fnfhRRpbjME5M6UubriIsQbb1XvEtsCiWVP/P/HZV4cTjJHpLkp4Iv2ZPTEggzUUXDdQuo0kzuktqVnx2ulhKEMNueF7c="
    template:
     - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}"
     - "Latest commit: %{commit_message} - by %{author}"
     - "Result:  %{result} in %{duration}"
