# Application's port
port: 8090
livenessPort: 8091
publicUrl: http://localhost:8080
jena:
  # Base IRI for all metadata entities
  metadataBaseIRI: "http://localhost/iri/"
  # Jena's TDB2 database path
  datasetPath: "data/db"
  storeParams:
    tdb.file_mode: "mapped"
    tdb.block_size: 8192
    tdb.block_read_cache_size: 5000
    tdb.block_write_cache_size: 1000
    tdb.node2nodeid_cache_size: 200000
    tdb.nodeid2node_cache_size: 750000
    tdb.node_miss_cache_size: 1000
    tdb.nodetable: "nodes"
    tdb.triple_index_primary: "SPO"
    tdb.triple_indexes:
      - "SPO"
      - "POS"
      - "OSP"
    tdb.quad_index_primary: "GSPO"
    tdb.quad_indexes:
      - "GSPO"
      - "GPOS"
      - "GOSP"
      - "POSG"
      - "OSPG"
      - "SPOG"
    tdb.prefixtable: "prefixes"
    tdb.prefix_index_primary: "GPU"
    tdb.prefix_indexes:
      - "GPU"
  # Path of the transaction log
  transactionLogPath: "data/log"
  bulkTransactions: true
auth:
  authServerUrl: http://localhost:5100/auth/
  realm: fairspace
  clientId: workspace-client
  clientSecret: '**********'
  enableBasicAuth: true
  superAdminUser: organisation-admin
webDAV:
  # Path of the WebDAV's local blob store
  blobStorePath: "data/blobs"
services:
  jupyterhub: https://jupyter.org/hub#
  cbioportal: https://www.cbioportal.org
  "test username": http://google.com?q=${username}
features:
viewDatabase:
  enabled: true
  url: jdbc:postgresql://localhost:9432/fairspace
search:
  pageRequestTimeout: 10000
  countRequestTimeout: 60000
