version: '3'

services:
  fairspace-keycloak-postgres:
    image: postgres:11-alpine
    container_name: fairspace-keycloak-database
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - fairspace-keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - fairspace-keycloak-db-network
    restart: unless-stopped
    logging:
      driver: ${DOCKER_LOGGING_DRIVER:-journald}
      options:
        labels: application
        tag: fairspace-keycloak-postgres

  fairspace-keycloak:
    image: jboss/keycloak:16.1.1
    container_name: fairspace-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: fairspace-keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME:?Please configure KEYCLOAK_HOSTNAME.}
      KEYCLOAK_HTTP_PORT: ${KEYCLOAK_PORT:-5100}
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:?Please configure KEYCLOAK_REALM}
      WORKSPACE_CLIENT_ID: ${WORKSPACE_CLIENT_ID:?Please configure WORKSPACE_CLIENT_ID}
      PROXY_ADDRESS_FORWARDING: 'true'
      WORKSPACE_URL: ${WORKSPACE_URL:?Please configure WORKSPACE_URL.}
      WORKSPACE_DEBUG_URL: ${WORKSPACE_DEBUG_URL:?Please configure WORKSPACE_DEBUG_URL.}
    ports:
      - ${KEYCLOAK_PORT:-5100}:8080
    depends_on:
      - fairspace-keycloak-postgres
    networks:
      - fairspace-keycloak-db-network
    volumes:
      - ./keycloak/setup-realm.sh:/opt/jboss/startup-scripts/setup-realm.sh
      - ./keycloak/realm-template.json:/tmp/realm-template.json
      - ./keycloak/keycloak-add-user.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
    restart: unless-stopped
    logging:
      driver: ${DOCKER_LOGGING_DRIVER:-journald}
      options:
        labels: application
        tag: fairspace-keycloak

  fairspace-postgres:
    image: postgres:13-alpine
    container_name: fairspace-postgresql
    environment:
      POSTGRES_DB: fairspace
      POSTGRES_USER: fairspace
      POSTGRES_PASSWORD: fairspace
    ports:
      - ${POSTGRESQL_PORT:-9432}:5432
    volumes:
      - fairspace-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: ${DOCKER_LOGGING_DRIVER:-journald}
      options:
        labels: application
        tag: fairspace-postgres

volumes:
  fairspace-keycloak-postgres-data:
  fairspace-postgres-data:

networks:
  fairspace-keycloak-db-network:
    driver: bridge
